name: Build and Push Docker Image

on:
  push:
    branches: ["main"]  # Запускать при пуше в main
  pull_request: {}      # Или при PR (опционально)

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # Название образа = имя репозитория

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Даёт права на запись в GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .                      # Путь к Dockerfile (в корне)
          file: ./Dockerfile              # Явно указываем Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}  # Пушим только в main
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify Image
        run: |
          echo "Image pushed to:"
          echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"
          echo "${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"